import type { Artist } from "./types";

export const artists: Artist[] = [
  {
    slug: "orphee-nyny",
    name: "Orphée NYNY",
    stageName: "Orphée NYNY",
    discipline: "Auteure-compositrice-interprète",
    bio: "Artiste gabonaise, Orphée NYNY fait dialoguer le jazz, le R&B et les sonorités traditionnelles dans un univers profondément sensible. Sa musique explore les émotions, l'identité et la mémoire, avec une élégance qui lui est propre.",
    artisticUniverse:
      "Nous l'accompagnons dans la structuration de sa carrière et le développement de son image artistique.",
    photoUrl: "/artists/orphee-nyny.avif",
    gallery: [],
    streamingLinks: {},
    socialLinks: {},
    bookingContact: null,
    schemaType: "Person",
    displayOrder: 1,
  },
  {
    slug: "eloquent-grand-b",
    name: "Éloquent Grand B",
    stageName: "Éloquent Grand B",
    discipline: "Poète, slameur, chanteur, guitariste et enseignant",
    bio: "Artiste multidisciplinaire, Éloquent Grand B fait de la parole un outil de transmission et de transformation. Entre poésie, musique et engagement, son travail célèbre les cultures africaines et invite à la réflexion.",
    artisticUniverse:
      "Notre accompagnement porte sur son développement professionnel, sa structuration administrative et la valorisation de ses projets.",
    photoUrl: "/artists/Eloquent-Grand-B.avif",
    gallery: [],
    streamingLinks: {},
    socialLinks: {},
    bookingContact: null,
    schemaType: "Person",
    displayOrder: 2,
  },
  {
    slug: "pindi",
    name: "PINDI",
    stageName: "PINDI",
    discipline: "Collectif artistique",
    bio: "PINDI puise sa force dans les traditions du sud du Gabon pour créer une œuvre résolument contemporaine. Spoken word, hip-hop, jazz, musiques du monde et rythmes ancestraux se rencontrent pour raconter une Afrique vivante, fière de son héritage et tournée vers l'avenir.",
    artisticUniverse:
      "Nous accompagnons le groupe dans son développement stratégique, la structuration de ses projets et son rayonnement, jusqu'à la scène internationale.",
    photoUrl: "/artists/Pindi.avif",
    gallery: [],
    streamingLinks: {},
    socialLinks: {},
    bookingContact: null,
    schemaType: "MusicGroup",
    displayOrder: 3,
  },
  {
    slug: "nans",
    name: "Nan's",
    stageName: "Nan's",
    discipline: "Nouvelle génération",
    bio: "Nan's construit un univers musical sincère et accessible. À travers des titres comme « Décroche », il touche le public avec des œuvres qui parlent du quotidien et des réalités de sa génération.",
    artisticUniverse:
      "Nous l'accompagnons dans sa stratégie de diffusion, sa présence sur les plateformes numériques et le développement de sa communication.",
    photoUrl: null,
    gallery: [],
    streamingLinks: {},
    socialLinks: {},
    bookingContact: null,
    schemaType: "Person",
    displayOrder: 4,
  },
  {
    slug: "ndoki",
    name: "Ndoki",
    stageName: "Ndoki",
    discipline: "Artiste en structuration",
    bio: "Animé par la volonté de bâtir une carrière solide et durable, Ndoki est convaincu que la réussite artistique repose autant sur le talent que sur l'organisation.",
    artisticUniverse:
      "Il bénéficie de notre accompagnement pour développer les fondations administratives et professionnelles de son parcours.",
    photoUrl: "/artists/Ndoki.avif",
    gallery: [],
    streamingLinks: {},
    socialLinks: {},
    bookingContact: null,
    schemaType: "Person",
    displayOrder: 5,
  },
  {
    slug: "tina-minkoue",
    name: "Tina Minkoué",
    stageName: "Tina Minkoué",
    discipline: "Artiste et porteuse de projets culturels",
    bio: "Tina Minkoué place la découverte des talents et la transmission au cœur de son engagement. À travers des initiatives comme « Lalala Ndoua », elle offre une scène aux artistes émergents et dynamise la vie culturelle gabonaise.",
    artisticUniverse: "Nous l'accompagnons dans la structuration et la promotion de ses projets.",
    photoUrl: null,
    gallery: [],
    streamingLinks: {},
    socialLinks: {},
    bookingContact: null,
    schemaType: "Person",
    displayOrder: 6,
  },
];
